// @/data.ts
export const database: Record<string, string[]> = {
    life: [
        "The wound is the place where the light enters you.",
        "You don't find peace by rearranging the world — you find it by rearranging your mind.",
        "Sometimes the bravest thing you can do is keep going when you want to give up.",
        "Your life is your canvas. Stop waiting for permission to paint.",
        "Growth begins the moment you decide your comfort zone is no longer enough.",
        "The storm doesn't last forever. You're allowed to be a work in progress.",
        "You are not your past. You are what you choose to become today.",
        "Healing doesn't mean the damage never existed — it means it no longer controls you.",
        "Some chapters close without closure. Write the next one anyway.",
        "Be patient with yourself. Nothing in nature blooms all year.",
        "You were born with wings — stop crawling through life.",
        "The strongest people aren't those who never cry — they're the ones who do and keep going.",
        "Your value doesn't decrease based on someone's inability to see your worth.",
        "One day you'll look back and realize the hardest times built your strongest self.",
        "It's okay to not be okay. It's not okay to stay there.",
        "The comeback is always stronger than the setback.",
        "You're not failing — you're learning how to fly.",
        "Let go of who you were to become who you're meant to be.",
        "Some people come into your life as lessons, not blessings.",
        "Your soul knows the way. Trust it.",
        "The universe always falls in love with a stubborn heart.",
        "Stop breaking your own heart by trying to fix others.",
        "You deserve the love you keep trying to give everyone else.",
        "Silence isn't empty — it's full of answers.",
        "And still, like dust, I'll rise.",
    ],

    lifestory: [
        "She was 17 when she realized her mother never hugged her. At 34, she hugged her own daughter so hard the little girl laughed and said, 'Mom, I can't breathe!' — and she cried because she finally understood love.",
        "He spent 10 years climbing the corporate ladder, only to realize it was leaning against the wrong wall. He quit on a Tuesday, bought a van on Wednesday, and hasn't worn shoes since 2021.",
        "The day her father died, she found a letter in his wallet addressed to 'My Future Daughter'. It simply said: 'I was proud of you before you were born.' She keeps it in her phone case now.",
        "He failed the exam three times. On the fourth attempt, he passed — but the real victory was learning to forgive himself for not being perfect the first time.",
        "She left the toxic relationship with nothing but a suitcase and her cat. Two years later, she owns a bakery called 'Second Chances' and the cat has an Instagram with 40k followers.",
        "He was homeless at 19. Today he runs a shelter that feeds 300 people a night. His rule: 'Everyone eats — no questions asked.'",
        "She survived cancer twice. Now she teaches art to kids who are still fighting. Her favorite phrase: 'Scars are just tattoos with better stories.'",
        "He lost his voice after the accident. Learned sign language. Now he teaches hearing people how silence can speak louder than words.",
        "She was told she'd never walk again. Walked down the aisle at her wedding 7 years later — in red high heels, just to prove them wrong.",
        "He wrote 365 letters to his younger self and buried them in the backyard. Plans to dig them up when he's 80.",
        "She grew up in foster care. Adopted a teenager last year. The first thing she said: 'Welcome home. This time it's forever.'",
        "He was bullied for stuttering. Became a radio DJ. Now millions listen to the voice they once mocked.",
        "She planted a tree the day her son died. Every year on his birthday, she reads him a letter beneath its branches.",
        "He forgave the man who killed his brother. Not for him — for the peace he finally found in his own heart.",
        "She was 400 pounds. Lost 220. Her before-and-after photo isn't what inspires people — it's the smile that finally matches her eyes.",
        "He came out at 67. His grandson said, 'Grandpa, love is love.' Best day of his life.",
        "She was abandoned at a train station as a baby. Found her birth mother 40 years later — only to adopt her when dementia took her memories.",
        "He survived suicide. Now has a semicolon tattoo and answers crisis hotlines at 3 AM.",
        "She learned to read at 92. Her first book? 'I Can and I Will.'",
        "He built a tiny home for the homeless man who once shared his last sandwich. They’re best friends now.",
        "She was infertile. Adopted twins. Years later, got pregnant naturally. Calls them her three miracles.",
        "He lost everything in the fire. Rebuilt his house — and his life — one brick of gratitude at a time.",
        "She was the quiet kid in class. Now she’s a world-famous poet. Her first book is titled 'I Was Always Speaking.'",
        "He was blind from birth. Invented an app that describes the world through sound. Says he 'sees' more clearly than most.",
    ],

    love: [
        "I loved you at your darkest — and I'll love you through every sunrise after.",
        "You are my safe place in a world that sometimes feels too loud.",
        "I didn't fall in love with you. I walked into love with you — eyes wide open.",
        "Some souls just understand each other upon meeting.",
        "You are my favorite notification.",
        "I love you not only for who you are, but for who I become when I'm with you.",
        "In your arms, I found the home I never knew I was looking for.",
        "You are the peace I always prayed for.",
        "I choose you. And I'll choose you over and over — without pause, without doubt, in a heartbeat.",
        "Your voice is my favorite sound.",
        "You are my today and all of my tomorrows.",
        "Loving you feels like breathing — effortless and essential.",
        "You make my heart smile in a way no one else ever could.",
        "I love you more than yesterday, but not as much as tomorrow.",
        "You are the best part of my ordinary days.",
        "With you, I am home.",
        "You are my sun, my moon, and all my stars.",
        "I still get butterflies even when I know exactly how the story ends.",
        "You are my favorite place to go when my mind searches for peace.",
        "I love you in ways I've never loved anyone — and in ways I didn't know I could.",
        "You are the risk I'll always take.",
        "My heart understood you before my mind did.",
        "You are my answered prayer.",
        "I love you louder than thunder and softer than rain.",
        "Forever is not long enough when I'm with you.",
    ],

    career: [
        "Your salary is the bribe they give you to forget your dreams.",
        "Don't wait for opportunity — create it.",
        "The expert in anything was once a beginner.",
        "Stop being afraid of what could go wrong and start being excited about what could go right.",
        "Your network is your net worth.",
        "Success is not final, failure is not fatal — it's the courage to continue that counts.",
        "Work hard in silence. Let your success be the noise.",
        "The only way to do great work is to love what you do.",
        "Don't wish for it — work for it.",
        "Your future is created by what you do today, not tomorrow.",
        "Hustle until your haters ask if you're hiring.",
        "Dream big. Work hard. Stay focused.",
        "Success doesn't come from what you do occasionally — it comes from what you do consistently.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Stop doubting yourself. Work hard and make it happen.",
        "You didn't come this far to only come this far.",
        "Be so good they can't ignore you.",
        "Your only limit is you.",
        "Great things never come from comfort zones.",
        "If it doesn't challenge you, it won't change you.",
        "Turn your can'ts into cans and your dreams into plans.",
        "Success is liking yourself, liking what you do, and liking how you do it.",
        "Don't stop when you're tired. Stop when you're done.",
        "The dream is free. The hustle is sold separately.",
        "Prove them wrong.",
    ],

    pain: [
        "It's okay to not be okay. Just don't stay there.",
        "You don't have to smile through the pain. You're allowed to feel it.",
        "Some days are heavier than others. That's okay.",
        "Your trauma is valid. Your pain is real. Your healing matters.",
        "Be gentle with yourself — you're doing the best you can.",
        "You are not weak for needing time to heal.",
        "The fact that you're still trying is proof you're strong.",
        "It's okay to fall apart sometimes. Tacos fall apart and we still love them.",
        "You don't have to be positive all the time. It's okay to feel broken.",
        "Some wounds take longer to heal — and that's okay.",
        "You're allowed to scream. You're allowed to cry. You're allowed to be angry.",
        "Healing is not linear.",
        "You don't have to have it all together. You're human.",
        "Your feelings are valid — even the messy ones.",
        "It's okay to ask for help. It doesn't make you weak.",
        "You are not your worst day.",
        "Pain changes you. It doesn't have to destroy you.",
        "You're allowed to take up space while you heal.",
        "Some battles have to be fought alone — but you don't have to lose them.",
        "You are worthy of love — especially from yourself.",
        "The night is darkest just before the dawn.",
        "Your story isn't over yet.",
        "You are stronger than you think — because you've survived everything so far.",
        "One day this pain will make sense.",
        "You don't have to rush your healing.",
    ],
};